// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: re.cardco.blackjack.table
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use std::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime, Did};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// Establishes a blackjack table. First record in any game. All players must agree on this before the game begins. One seat banks each round (rotating); the others wager against the banker's stack.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct Table<'a> {
    pub created_at: Datetime,
    ///Minimum wager per round. Short stacks may wager all-in below it.
    pub min_bet: i64,
    ///Player DIDs in seat order. A freshly-created open room may list only the host (length 1); the roster grows as the host admits joiners.
    #[serde(borrow)]
    pub players: Vec<Did<'a>>,
    ///Set by the host when the roster is locked and the game begins. Absent while the room is still open for joiners. Once present, players reference this record as the canonical table for the game.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<Datetime>,
    ///Starting chip count for each player.
    pub starting_chips: i64,
    ///Bumped periodically by a joining player while they wait to be admitted, so a host that missed the original join-request commit (dropped socket, late subscribe) discovers it from a later one.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Datetime>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct TableGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: Table<'a>,
}

impl<'a> Table<'a> {
    pub fn uri(uri: impl Into<CowStr<'a>>) -> Result<RecordUri<'a, TableRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct TableRecord;
impl XrpcResp for TableRecord {
    const NSID: &'static str = "re.cardco.blackjack.table";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = TableGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<TableGetRecordOutput<'_>> for Table<'_> {
    fn from(output: TableGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for Table<'_> {
    const NSID: &'static str = "re.cardco.blackjack.table";
    type Record = TableRecord;
}

impl Collection for TableRecord {
    const NSID: &'static str = "re.cardco.blackjack.table";
    type Record = TableRecord;
}

impl<'a> LexiconSchema for Table<'a> {
    fn nsid() -> &'static str {
        "re.cardco.blackjack.table"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_blackjack_table()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.min_bet;
            if *value < 1i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("min_bet"),
                    min: 1i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.players;
            #[allow(unused_comparisons)]
            if value.len() > 6usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("players"),
                    max: 6usize,
                    actual: value.len(),
                });
            }
        }
        {
            let value = &self.players;
            #[allow(unused_comparisons)]
            if value.len() < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("players"),
                    min: 1usize,
                    actual: value.len(),
                });
            }
        }
        {
            let value = &self.starting_chips;
            if *value < 1i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("starting_chips"),
                    min: 1i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod table_state {
    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type MinBet;
        type StartingChips;
        type CreatedAt;
        type Players;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type MinBet = Unset;
        type StartingChips = Unset;
        type CreatedAt = Unset;
        type Players = Unset;
    }
    ///State transition - sets the `min_bet` field to Set
    pub struct SetMinBet<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetMinBet<S> {}
    impl<S: State> State for SetMinBet<S> {
        type MinBet = Set<members::min_bet>;
        type StartingChips = S::StartingChips;
        type CreatedAt = S::CreatedAt;
        type Players = S::Players;
    }
    ///State transition - sets the `starting_chips` field to Set
    pub struct SetStartingChips<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetStartingChips<S> {}
    impl<S: State> State for SetStartingChips<S> {
        type MinBet = S::MinBet;
        type StartingChips = Set<members::starting_chips>;
        type CreatedAt = S::CreatedAt;
        type Players = S::Players;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type MinBet = S::MinBet;
        type StartingChips = S::StartingChips;
        type CreatedAt = Set<members::created_at>;
        type Players = S::Players;
    }
    ///State transition - sets the `players` field to Set
    pub struct SetPlayers<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetPlayers<S> {}
    impl<S: State> State for SetPlayers<S> {
        type MinBet = S::MinBet;
        type StartingChips = S::StartingChips;
        type CreatedAt = S::CreatedAt;
        type Players = Set<members::players>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `min_bet` field
        pub struct min_bet(());
        ///Marker type for the `starting_chips` field
        pub struct starting_chips(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `players` field
        pub struct players(());
    }
}

/// Builder for constructing an instance of this type
pub struct TableBuilder<'a, S: table_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<Datetime>,
        Option<i64>,
        Option<Vec<Did<'a>>>,
        Option<Datetime>,
        Option<i64>,
        Option<Datetime>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Table<'a> {
    /// Create a new builder for this type
    pub fn new() -> TableBuilder<'a, table_state::Empty> {
        TableBuilder::new()
    }
}

impl<'a> TableBuilder<'a, table_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        TableBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TableBuilder<'a, S>
where
    S: table_state::State,
    S::CreatedAt: table_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> TableBuilder<'a, table_state::SetCreatedAt<S>> {
        self._fields.0 = Option::Some(value.into());
        TableBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TableBuilder<'a, S>
where
    S: table_state::State,
    S::MinBet: table_state::IsUnset,
{
    /// Set the `minBet` field (required)
    pub fn min_bet(mut self, value: impl Into<i64>) -> TableBuilder<'a, table_state::SetMinBet<S>> {
        self._fields.1 = Option::Some(value.into());
        TableBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TableBuilder<'a, S>
where
    S: table_state::State,
    S::Players: table_state::IsUnset,
{
    /// Set the `players` field (required)
    pub fn players(
        mut self,
        value: impl Into<Vec<Did<'a>>>,
    ) -> TableBuilder<'a, table_state::SetPlayers<S>> {
        self._fields.2 = Option::Some(value.into());
        TableBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: table_state::State> TableBuilder<'a, S> {
    /// Set the `startedAt` field (optional)
    pub fn started_at(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `startedAt` field to an Option value (optional)
    pub fn maybe_started_at(mut self, value: Option<Datetime>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<'a, S> TableBuilder<'a, S>
where
    S: table_state::State,
    S::StartingChips: table_state::IsUnset,
{
    /// Set the `startingChips` field (required)
    pub fn starting_chips(
        mut self,
        value: impl Into<i64>,
    ) -> TableBuilder<'a, table_state::SetStartingChips<S>> {
        self._fields.4 = Option::Some(value.into());
        TableBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: table_state::State> TableBuilder<'a, S> {
    /// Set the `updatedAt` field (optional)
    pub fn updated_at(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `updatedAt` field to an Option value (optional)
    pub fn maybe_updated_at(mut self, value: Option<Datetime>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<'a, S> TableBuilder<'a, S>
where
    S: table_state::State,
    S::MinBet: table_state::IsSet,
    S::StartingChips: table_state::IsSet,
    S::CreatedAt: table_state::IsSet,
    S::Players: table_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Table<'a> {
        Table {
            created_at: self._fields.0.unwrap(),
            min_bet: self._fields.1.unwrap(),
            players: self._fields.2.unwrap(),
            started_at: self._fields.3,
            starting_chips: self._fields.4.unwrap(),
            updated_at: self._fields.5,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Table<'a> {
        Table {
            created_at: self._fields.0.unwrap(),
            min_bet: self._fields.1.unwrap(),
            players: self._fields.2.unwrap(),
            started_at: self._fields.3,
            starting_chips: self._fields.4.unwrap(),
            updated_at: self._fields.5,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_re_cardco_blackjack_table() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use std::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("re.cardco.blackjack.table"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Establishes a blackjack table. First record in any game. All players must agree on this before the game begins. One seat banks each round (rotating); the others wager against the banker's stack.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("players"),
                                SmolStr::new_static("startingChips"),
                                SmolStr::new_static("minBet"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("minBet"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(1i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("players"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Player DIDs in seat order. A freshly-created open room may list only the host (length 1); the roster grows as the host admits joiners.",
                                        ),
                                    ),
                                    items: LexArrayItem::String(LexString {
                                        format: Some(LexStringFormat::Did),
                                        ..Default::default()
                                    }),
                                    min_length: Some(1usize),
                                    max_length: Some(6usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("startedAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Set by the host when the roster is locked and the game begins. Absent while the room is still open for joiners. Once present, players reference this record as the canonical table for the game.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("startingChips"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(1i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("updatedAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Bumped periodically by a joining player while they wait to be admitted, so a host that missed the original join-request commit (dropped socket, late subscribe) discovers it from a later one.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
