// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: re.cardco.poker.action
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use std::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon, open_union};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::lexicon::re_cardco::poker::Bet;
use crate::lexicon::re_cardco::poker::CommitSeed;
use crate::lexicon::re_cardco::poker::LockDeck;
use crate::lexicon::re_cardco::poker::RevealHand;
use crate::lexicon::re_cardco::poker::RevealLockKey;
use crate::lexicon::re_cardco::poker::ShuffleDeck;
use crate::lexicon::re_cardco::poker::VerifySeed;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// A single action in a poker hand. Key format: {table-tid}-{sequence-number}. Each action chains back to the previous via prev.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "re.cardco.poker.action",
    tag = "$type"
)]
pub struct Action<'a> {
    ///The action payload.
    #[serde(borrow)]
    pub action: ActionAction<'a>,
    pub created_at: Datetime,
    ///Reference to the previous action in this hand. Absent for the first action (seq 0).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub prev: Option<Data<'a>>,
    ///Action sequence number within this hand, starting from 0.
    pub seq: i64,
    ///Reference to the table record for this hand.
    #[serde(borrow)]
    pub table: Data<'a>,
}

#[open_union]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(tag = "$type", bound(deserialize = "'de: 'a"))]
pub enum ActionAction<'a> {
    #[serde(rename = "re.cardco.poker.defs#commitSeed")]
    CommitSeed(Box<CommitSeed<'a>>),
    #[serde(rename = "re.cardco.poker.defs#shuffleDeck")]
    ShuffleDeck(Box<ShuffleDeck<'a>>),
    #[serde(rename = "re.cardco.poker.defs#lockDeck")]
    LockDeck(Box<LockDeck<'a>>),
    #[serde(rename = "re.cardco.poker.defs#revealLockKey")]
    RevealLockKey(Box<RevealLockKey<'a>>),
    #[serde(rename = "re.cardco.poker.defs#bet")]
    Bet(Box<Bet<'a>>),
    #[serde(rename = "re.cardco.poker.defs#revealHand")]
    RevealHand(Box<RevealHand<'a>>),
    #[serde(rename = "re.cardco.poker.defs#verifySeed")]
    VerifySeed(Box<VerifySeed<'a>>),
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ActionGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: Action<'a>,
}

impl<'a> Action<'a> {
    pub fn uri(uri: impl Into<CowStr<'a>>) -> Result<RecordUri<'a, ActionRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct ActionRecord;
impl XrpcResp for ActionRecord {
    const NSID: &'static str = "re.cardco.poker.action";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ActionGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<ActionGetRecordOutput<'_>> for Action<'_> {
    fn from(output: ActionGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for Action<'_> {
    const NSID: &'static str = "re.cardco.poker.action";
    type Record = ActionRecord;
}

impl Collection for ActionRecord {
    const NSID: &'static str = "re.cardco.poker.action";
    type Record = ActionRecord;
}

impl<'a> LexiconSchema for Action<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.action"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_action()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.seq;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("seq"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod action_state {

    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Table;
        type CreatedAt;
        type Action;
        type Seq;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Table = Unset;
        type CreatedAt = Unset;
        type Action = Unset;
        type Seq = Unset;
    }
    ///State transition - sets the `table` field to Set
    pub struct SetTable<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTable<S> {}
    impl<S: State> State for SetTable<S> {
        type Table = Set<members::table>;
        type CreatedAt = S::CreatedAt;
        type Action = S::Action;
        type Seq = S::Seq;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Table = S::Table;
        type CreatedAt = Set<members::created_at>;
        type Action = S::Action;
        type Seq = S::Seq;
    }
    ///State transition - sets the `action` field to Set
    pub struct SetAction<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetAction<S> {}
    impl<S: State> State for SetAction<S> {
        type Table = S::Table;
        type CreatedAt = S::CreatedAt;
        type Action = Set<members::action>;
        type Seq = S::Seq;
    }
    ///State transition - sets the `seq` field to Set
    pub struct SetSeq<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSeq<S> {}
    impl<S: State> State for SetSeq<S> {
        type Table = S::Table;
        type CreatedAt = S::CreatedAt;
        type Action = S::Action;
        type Seq = Set<members::seq>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `table` field
        pub struct table(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `action` field
        pub struct action(());
        ///Marker type for the `seq` field
        pub struct seq(());
    }
}

/// Builder for constructing an instance of this type
pub struct ActionBuilder<'a, S: action_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<ActionAction<'a>>,
        Option<Datetime>,
        Option<Data<'a>>,
        Option<i64>,
        Option<Data<'a>>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Action<'a> {
    /// Create a new builder for this type
    pub fn new() -> ActionBuilder<'a, action_state::Empty> {
        ActionBuilder::new()
    }
}

impl<'a> ActionBuilder<'a, action_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ActionBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ActionBuilder<'a, S>
where
    S: action_state::State,
    S::Action: action_state::IsUnset,
{
    /// Set the `action` field (required)
    pub fn action(
        mut self,
        value: impl Into<ActionAction<'a>>,
    ) -> ActionBuilder<'a, action_state::SetAction<S>> {
        self._fields.0 = Option::Some(value.into());
        ActionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ActionBuilder<'a, S>
where
    S: action_state::State,
    S::CreatedAt: action_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> ActionBuilder<'a, action_state::SetCreatedAt<S>> {
        self._fields.1 = Option::Some(value.into());
        ActionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: action_state::State> ActionBuilder<'a, S> {
    /// Set the `prev` field (optional)
    pub fn prev(mut self, value: impl Into<Option<Data<'a>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `prev` field to an Option value (optional)
    pub fn maybe_prev(mut self, value: Option<Data<'a>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<'a, S> ActionBuilder<'a, S>
where
    S: action_state::State,
    S::Seq: action_state::IsUnset,
{
    /// Set the `seq` field (required)
    pub fn seq(mut self, value: impl Into<i64>) -> ActionBuilder<'a, action_state::SetSeq<S>> {
        self._fields.3 = Option::Some(value.into());
        ActionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ActionBuilder<'a, S>
where
    S: action_state::State,
    S::Table: action_state::IsUnset,
{
    /// Set the `table` field (required)
    pub fn table(
        mut self,
        value: impl Into<Data<'a>>,
    ) -> ActionBuilder<'a, action_state::SetTable<S>> {
        self._fields.4 = Option::Some(value.into());
        ActionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ActionBuilder<'a, S>
where
    S: action_state::State,
    S::Table: action_state::IsSet,
    S::CreatedAt: action_state::IsSet,
    S::Action: action_state::IsSet,
    S::Seq: action_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Action<'a> {
        Action {
            action: self._fields.0.unwrap(),
            created_at: self._fields.1.unwrap(),
            prev: self._fields.2,
            seq: self._fields.3.unwrap(),
            table: self._fields.4.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<jacquard_common::deps::smol_str::SmolStr, Data<'a>>,
    ) -> Action<'a> {
        Action {
            action: self._fields.0.unwrap(),
            created_at: self._fields.1.unwrap(),
            prev: self._fields.2,
            seq: self._fields.3.unwrap(),
            table: self._fields.4.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_re_cardco_poker_action() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use std::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("re.cardco.poker.action"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A single action in a poker hand. Key format: {table-tid}-{sequence-number}. Each action chains back to the previous via prev.",
                        ),
                    ),
                    key: Some(CowStr::new_static("any")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("table"), SmolStr::new_static("seq"),
                                SmolStr::new_static("action"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("action"),
                                LexObjectProperty::Union(LexRefUnion {
                                    description: Some(
                                        CowStr::new_static("The action payload."),
                                    ),
                                    refs: vec![
                                        CowStr::new_static("re.cardco.poker.defs#commitSeed"),
                                        CowStr::new_static("re.cardco.poker.defs#shuffleDeck"),
                                        CowStr::new_static("re.cardco.poker.defs#lockDeck"),
                                        CowStr::new_static("re.cardco.poker.defs#revealLockKey"),
                                        CowStr::new_static("re.cardco.poker.defs#bet"),
                                        CowStr::new_static("re.cardco.poker.defs#revealHand"),
                                        CowStr::new_static("re.cardco.poker.defs#verifySeed")
                                    ],
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("prev"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("seq"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("table"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
