// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: re.cardco.poker.bet
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use std::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// A betting action: fold, check, call, raise, or all-in.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", rename = "re.cardco.poker.bet", tag = "$type")]
pub struct Bet<'a> {
    ///The betting action. For raises, use 'raise' with the amount field.
    #[serde(borrow)]
    pub action: BetAction<'a>,
    ///Raise amount (total, not incremental). Only present for raises.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<i64>,
    pub created_at: Datetime,
    #[serde(borrow)]
    pub table: Data<'a>,
}

/// The betting action. For raises, use 'raise' with the amount field.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum BetAction<'a> {
    Fold,
    Check,
    Call,
    AllIn,
    Other(CowStr<'a>),
}

impl<'a> BetAction<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Fold => "fold",
            Self::Check => "check",
            Self::Call => "call",
            Self::AllIn => "allIn",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for BetAction<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "fold" => Self::Fold,
            "check" => Self::Check,
            "call" => Self::Call,
            "allIn" => Self::AllIn,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for BetAction<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "fold" => Self::Fold,
            "check" => Self::Check,
            "call" => Self::Call,
            "allIn" => Self::AllIn,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for BetAction<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for BetAction<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for BetAction<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for BetAction<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for BetAction<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for BetAction<'_> {
    type Output = BetAction<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            BetAction::Fold => BetAction::Fold,
            BetAction::Check => BetAction::Check,
            BetAction::Call => BetAction::Call,
            BetAction::AllIn => BetAction::AllIn,
            BetAction::Other(v) => BetAction::Other(v.into_static()),
        }
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct BetGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: Bet<'a>,
}

impl<'a> Bet<'a> {
    pub fn uri(
        uri: impl Into<CowStr<'a>>,
    ) -> Result<RecordUri<'a, BetRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct BetRecord;
impl XrpcResp for BetRecord {
    const NSID: &'static str = "re.cardco.poker.bet";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = BetGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<BetGetRecordOutput<'_>> for Bet<'_> {
    fn from(output: BetGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for Bet<'_> {
    const NSID: &'static str = "re.cardco.poker.bet";
    type Record = BetRecord;
}

impl Collection for BetRecord {
    const NSID: &'static str = "re.cardco.poker.bet";
    type Record = BetRecord;
}

impl<'a> LexiconSchema for Bet<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.bet"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_bet()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.amount {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("amount"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod bet_state {

    pub use crate::lexicon::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Action;
        type Table;
        type CreatedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Action = Unset;
        type Table = Unset;
        type CreatedAt = Unset;
    }
    ///State transition - sets the `action` field to Set
    pub struct SetAction<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetAction<S> {}
    impl<S: State> State for SetAction<S> {
        type Action = Set<members::action>;
        type Table = S::Table;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `table` field to Set
    pub struct SetTable<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTable<S> {}
    impl<S: State> State for SetTable<S> {
        type Action = S::Action;
        type Table = Set<members::table>;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Action = S::Action;
        type Table = S::Table;
        type CreatedAt = Set<members::created_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `action` field
        pub struct action(());
        ///Marker type for the `table` field
        pub struct table(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
    }
}

/// Builder for constructing an instance of this type
pub struct BetBuilder<'a, S: bet_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<BetAction<'a>>, Option<i64>, Option<Datetime>, Option<Data<'a>>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Bet<'a> {
    /// Create a new builder for this type
    pub fn new() -> BetBuilder<'a, bet_state::Empty> {
        BetBuilder::new()
    }
}

impl<'a> BetBuilder<'a, bet_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        BetBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> BetBuilder<'a, S>
where
    S: bet_state::State,
    S::Action: bet_state::IsUnset,
{
    /// Set the `action` field (required)
    pub fn action(
        mut self,
        value: impl Into<BetAction<'a>>,
    ) -> BetBuilder<'a, bet_state::SetAction<S>> {
        self._fields.0 = Option::Some(value.into());
        BetBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: bet_state::State> BetBuilder<'a, S> {
    /// Set the `amount` field (optional)
    pub fn amount(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `amount` field to an Option value (optional)
    pub fn maybe_amount(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<'a, S> BetBuilder<'a, S>
where
    S: bet_state::State,
    S::CreatedAt: bet_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> BetBuilder<'a, bet_state::SetCreatedAt<S>> {
        self._fields.2 = Option::Some(value.into());
        BetBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> BetBuilder<'a, S>
where
    S: bet_state::State,
    S::Table: bet_state::IsUnset,
{
    /// Set the `table` field (required)
    pub fn table(
        mut self,
        value: impl Into<Data<'a>>,
    ) -> BetBuilder<'a, bet_state::SetTable<S>> {
        self._fields.3 = Option::Some(value.into());
        BetBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> BetBuilder<'a, S>
where
    S: bet_state::State,
    S::Action: bet_state::IsSet,
    S::Table: bet_state::IsSet,
    S::CreatedAt: bet_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Bet<'a> {
        Bet {
            action: self._fields.0.unwrap(),
            amount: self._fields.1,
            created_at: self._fields.2.unwrap(),
            table: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<jacquard_common::deps::smol_str::SmolStr, Data<'a>>,
    ) -> Bet<'a> {
        Bet {
            action: self._fields.0.unwrap(),
            amount: self._fields.1,
            created_at: self._fields.2.unwrap(),
            table: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_re_cardco_poker_bet() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use std::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("re.cardco.poker.bet"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A betting action: fold, check, call, raise, or all-in.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("table"), SmolStr::new_static("action"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("action"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The betting action. For raises, use 'raise' with the amount field.",
                                        ),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("amount"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("table"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}