// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: re.cardco.poker.revealLockKey
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use std::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_common::deps::bytes::Bytes;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// Reveal a per-position lock scalar to deal a card. Players create these during dealing rounds.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "re.cardco.poker.revealLockKey",
    tag = "$type"
)]
pub struct RevealLockKey<'a> {
    pub created_at: Datetime,
    ///Which card position in the deck is being revealed.
    pub deck_position: i64,
    ///Ristretto255 lock decryption scalar for this position.
    #[serde(with = "jacquard_common::serde_bytes_helper")]
    pub scalar: Bytes,
    #[serde(borrow)]
    pub table: Data<'a>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct RevealLockKeyGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: RevealLockKey<'a>,
}

impl<'a> RevealLockKey<'a> {
    pub fn uri(
        uri: impl Into<CowStr<'a>>,
    ) -> Result<RecordUri<'a, RevealLockKeyRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct RevealLockKeyRecord;
impl XrpcResp for RevealLockKeyRecord {
    const NSID: &'static str = "re.cardco.poker.revealLockKey";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = RevealLockKeyGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<RevealLockKeyGetRecordOutput<'_>> for RevealLockKey<'_> {
    fn from(output: RevealLockKeyGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for RevealLockKey<'_> {
    const NSID: &'static str = "re.cardco.poker.revealLockKey";
    type Record = RevealLockKeyRecord;
}

impl Collection for RevealLockKeyRecord {
    const NSID: &'static str = "re.cardco.poker.revealLockKey";
    type Record = RevealLockKeyRecord;
}

impl<'a> LexiconSchema for RevealLockKey<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.revealLockKey"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_revealLockKey()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.deck_position;
            if *value > 51i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("deck_position"),
                    max: 51i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.deck_position;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("deck_position"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod reveal_lock_key_state {

    pub use crate::lexicon::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Table;
        type DeckPosition;
        type CreatedAt;
        type Scalar;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Table = Unset;
        type DeckPosition = Unset;
        type CreatedAt = Unset;
        type Scalar = Unset;
    }
    ///State transition - sets the `table` field to Set
    pub struct SetTable<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTable<S> {}
    impl<S: State> State for SetTable<S> {
        type Table = Set<members::table>;
        type DeckPosition = S::DeckPosition;
        type CreatedAt = S::CreatedAt;
        type Scalar = S::Scalar;
    }
    ///State transition - sets the `deck_position` field to Set
    pub struct SetDeckPosition<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDeckPosition<S> {}
    impl<S: State> State for SetDeckPosition<S> {
        type Table = S::Table;
        type DeckPosition = Set<members::deck_position>;
        type CreatedAt = S::CreatedAt;
        type Scalar = S::Scalar;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Table = S::Table;
        type DeckPosition = S::DeckPosition;
        type CreatedAt = Set<members::created_at>;
        type Scalar = S::Scalar;
    }
    ///State transition - sets the `scalar` field to Set
    pub struct SetScalar<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetScalar<S> {}
    impl<S: State> State for SetScalar<S> {
        type Table = S::Table;
        type DeckPosition = S::DeckPosition;
        type CreatedAt = S::CreatedAt;
        type Scalar = Set<members::scalar>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `table` field
        pub struct table(());
        ///Marker type for the `deck_position` field
        pub struct deck_position(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `scalar` field
        pub struct scalar(());
    }
}

/// Builder for constructing an instance of this type
pub struct RevealLockKeyBuilder<'a, S: reveal_lock_key_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Datetime>, Option<i64>, Option<Bytes>, Option<Data<'a>>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> RevealLockKey<'a> {
    /// Create a new builder for this type
    pub fn new() -> RevealLockKeyBuilder<'a, reveal_lock_key_state::Empty> {
        RevealLockKeyBuilder::new()
    }
}

impl<'a> RevealLockKeyBuilder<'a, reveal_lock_key_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        RevealLockKeyBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealLockKeyBuilder<'a, S>
where
    S: reveal_lock_key_state::State,
    S::CreatedAt: reveal_lock_key_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> RevealLockKeyBuilder<'a, reveal_lock_key_state::SetCreatedAt<S>> {
        self._fields.0 = Option::Some(value.into());
        RevealLockKeyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealLockKeyBuilder<'a, S>
where
    S: reveal_lock_key_state::State,
    S::DeckPosition: reveal_lock_key_state::IsUnset,
{
    /// Set the `deckPosition` field (required)
    pub fn deck_position(
        mut self,
        value: impl Into<i64>,
    ) -> RevealLockKeyBuilder<'a, reveal_lock_key_state::SetDeckPosition<S>> {
        self._fields.1 = Option::Some(value.into());
        RevealLockKeyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealLockKeyBuilder<'a, S>
where
    S: reveal_lock_key_state::State,
    S::Scalar: reveal_lock_key_state::IsUnset,
{
    /// Set the `scalar` field (required)
    pub fn scalar(
        mut self,
        value: impl Into<Bytes>,
    ) -> RevealLockKeyBuilder<'a, reveal_lock_key_state::SetScalar<S>> {
        self._fields.2 = Option::Some(value.into());
        RevealLockKeyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealLockKeyBuilder<'a, S>
where
    S: reveal_lock_key_state::State,
    S::Table: reveal_lock_key_state::IsUnset,
{
    /// Set the `table` field (required)
    pub fn table(
        mut self,
        value: impl Into<Data<'a>>,
    ) -> RevealLockKeyBuilder<'a, reveal_lock_key_state::SetTable<S>> {
        self._fields.3 = Option::Some(value.into());
        RevealLockKeyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealLockKeyBuilder<'a, S>
where
    S: reveal_lock_key_state::State,
    S::Table: reveal_lock_key_state::IsSet,
    S::DeckPosition: reveal_lock_key_state::IsSet,
    S::CreatedAt: reveal_lock_key_state::IsSet,
    S::Scalar: reveal_lock_key_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> RevealLockKey<'a> {
        RevealLockKey {
            created_at: self._fields.0.unwrap(),
            deck_position: self._fields.1.unwrap(),
            scalar: self._fields.2.unwrap(),
            table: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<jacquard_common::deps::smol_str::SmolStr, Data<'a>>,
    ) -> RevealLockKey<'a> {
        RevealLockKey {
            created_at: self._fields.0.unwrap(),
            deck_position: self._fields.1.unwrap(),
            scalar: self._fields.2.unwrap(),
            table: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_re_cardco_poker_revealLockKey() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use std::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("re.cardco.poker.revealLockKey"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Reveal a per-position lock scalar to deal a card. Players create these during dealing rounds.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("table"),
                                SmolStr::new_static("deckPosition"),
                                SmolStr::new_static("scalar"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("deckPosition"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(51i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("scalar"),
                                LexObjectProperty::Bytes(LexBytes {
                                    max_length: Some(32usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("table"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}