// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: re.cardco.poker.revealHand
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use std::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_common::deps::bytes::Bytes;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::lexicon::re_cardco::poker::reveal_hand;
/// Reveal hole card lock keys at showdown.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", rename = "re.cardco.poker.revealHand", tag = "$type")]
pub struct RevealHand<'a> {
    pub created_at: Datetime,
    ///Lock key reveals for hole card positions.
    #[serde(borrow)]
    pub reveals: Vec<reveal_hand::PositionScalar<'a>>,
    #[serde(borrow)]
    pub table: Data<'a>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct RevealHandGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: RevealHand<'a>,
}


#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct PositionScalar<'a> {
    pub deck_position: i64,
    ///Ristretto255 lock decryption scalar.
    #[serde(with = "jacquard_common::serde_bytes_helper")]
    pub scalar: Bytes,
}

impl<'a> RevealHand<'a> {
    pub fn uri(
        uri: impl Into<CowStr<'a>>,
    ) -> Result<RecordUri<'a, RevealHandRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct RevealHandRecord;
impl XrpcResp for RevealHandRecord {
    const NSID: &'static str = "re.cardco.poker.revealHand";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = RevealHandGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<RevealHandGetRecordOutput<'_>> for RevealHand<'_> {
    fn from(output: RevealHandGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for RevealHand<'_> {
    const NSID: &'static str = "re.cardco.poker.revealHand";
    type Record = RevealHandRecord;
}

impl Collection for RevealHandRecord {
    const NSID: &'static str = "re.cardco.poker.revealHand";
    type Record = RevealHandRecord;
}

impl<'a> LexiconSchema for RevealHand<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.revealHand"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_revealHand()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<'a> LexiconSchema for PositionScalar<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.revealHand"
    }
    fn def_name() -> &'static str {
        "positionScalar"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_revealHand()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.deck_position;
            if *value > 51i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("deck_position"),
                    max: 51i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.deck_position;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("deck_position"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod reveal_hand_state {

    pub use crate::lexicon::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Reveals;
        type Table;
        type CreatedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Reveals = Unset;
        type Table = Unset;
        type CreatedAt = Unset;
    }
    ///State transition - sets the `reveals` field to Set
    pub struct SetReveals<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetReveals<S> {}
    impl<S: State> State for SetReveals<S> {
        type Reveals = Set<members::reveals>;
        type Table = S::Table;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `table` field to Set
    pub struct SetTable<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTable<S> {}
    impl<S: State> State for SetTable<S> {
        type Reveals = S::Reveals;
        type Table = Set<members::table>;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Reveals = S::Reveals;
        type Table = S::Table;
        type CreatedAt = Set<members::created_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `reveals` field
        pub struct reveals(());
        ///Marker type for the `table` field
        pub struct table(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
    }
}

/// Builder for constructing an instance of this type
pub struct RevealHandBuilder<'a, S: reveal_hand_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<Datetime>,
        Option<Vec<reveal_hand::PositionScalar<'a>>>,
        Option<Data<'a>>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> RevealHand<'a> {
    /// Create a new builder for this type
    pub fn new() -> RevealHandBuilder<'a, reveal_hand_state::Empty> {
        RevealHandBuilder::new()
    }
}

impl<'a> RevealHandBuilder<'a, reveal_hand_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        RevealHandBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealHandBuilder<'a, S>
where
    S: reveal_hand_state::State,
    S::CreatedAt: reveal_hand_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> RevealHandBuilder<'a, reveal_hand_state::SetCreatedAt<S>> {
        self._fields.0 = Option::Some(value.into());
        RevealHandBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealHandBuilder<'a, S>
where
    S: reveal_hand_state::State,
    S::Reveals: reveal_hand_state::IsUnset,
{
    /// Set the `reveals` field (required)
    pub fn reveals(
        mut self,
        value: impl Into<Vec<reveal_hand::PositionScalar<'a>>>,
    ) -> RevealHandBuilder<'a, reveal_hand_state::SetReveals<S>> {
        self._fields.1 = Option::Some(value.into());
        RevealHandBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealHandBuilder<'a, S>
where
    S: reveal_hand_state::State,
    S::Table: reveal_hand_state::IsUnset,
{
    /// Set the `table` field (required)
    pub fn table(
        mut self,
        value: impl Into<Data<'a>>,
    ) -> RevealHandBuilder<'a, reveal_hand_state::SetTable<S>> {
        self._fields.2 = Option::Some(value.into());
        RevealHandBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealHandBuilder<'a, S>
where
    S: reveal_hand_state::State,
    S::Reveals: reveal_hand_state::IsSet,
    S::Table: reveal_hand_state::IsSet,
    S::CreatedAt: reveal_hand_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> RevealHand<'a> {
        RevealHand {
            created_at: self._fields.0.unwrap(),
            reveals: self._fields.1.unwrap(),
            table: self._fields.2.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<jacquard_common::deps::smol_str::SmolStr, Data<'a>>,
    ) -> RevealHand<'a> {
        RevealHand {
            created_at: self._fields.0.unwrap(),
            reveals: self._fields.1.unwrap(),
            table: self._fields.2.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_re_cardco_poker_revealHand() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use std::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("re.cardco.poker.revealHand"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static("Reveal hole card lock keys at showdown."),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("table"),
                                SmolStr::new_static("reveals"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("reveals"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Lock key reveals for hole card positions.",
                                        ),
                                    ),
                                    items: LexArrayItem::Ref(LexRef {
                                        r#ref: CowStr::new_static("#positionScalar"),
                                        ..Default::default()
                                    }),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("table"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("positionScalar"),
                LexUserType::Object(LexObject {
                    required: Some(
                        vec![
                            SmolStr::new_static("deckPosition"),
                            SmolStr::new_static("scalar")
                        ],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("deckPosition"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                maximum: Some(51i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("scalar"),
                            LexObjectProperty::Bytes(LexBytes {
                                max_length: Some(32usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod position_scalar_state {

    pub use crate::lexicon::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type DeckPosition;
        type Scalar;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type DeckPosition = Unset;
        type Scalar = Unset;
    }
    ///State transition - sets the `deck_position` field to Set
    pub struct SetDeckPosition<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDeckPosition<S> {}
    impl<S: State> State for SetDeckPosition<S> {
        type DeckPosition = Set<members::deck_position>;
        type Scalar = S::Scalar;
    }
    ///State transition - sets the `scalar` field to Set
    pub struct SetScalar<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetScalar<S> {}
    impl<S: State> State for SetScalar<S> {
        type DeckPosition = S::DeckPosition;
        type Scalar = Set<members::scalar>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `deck_position` field
        pub struct deck_position(());
        ///Marker type for the `scalar` field
        pub struct scalar(());
    }
}

/// Builder for constructing an instance of this type
pub struct PositionScalarBuilder<'a, S: position_scalar_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<i64>, Option<Bytes>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> PositionScalar<'a> {
    /// Create a new builder for this type
    pub fn new() -> PositionScalarBuilder<'a, position_scalar_state::Empty> {
        PositionScalarBuilder::new()
    }
}

impl<'a> PositionScalarBuilder<'a, position_scalar_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        PositionScalarBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> PositionScalarBuilder<'a, S>
where
    S: position_scalar_state::State,
    S::DeckPosition: position_scalar_state::IsUnset,
{
    /// Set the `deckPosition` field (required)
    pub fn deck_position(
        mut self,
        value: impl Into<i64>,
    ) -> PositionScalarBuilder<'a, position_scalar_state::SetDeckPosition<S>> {
        self._fields.0 = Option::Some(value.into());
        PositionScalarBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> PositionScalarBuilder<'a, S>
where
    S: position_scalar_state::State,
    S::Scalar: position_scalar_state::IsUnset,
{
    /// Set the `scalar` field (required)
    pub fn scalar(
        mut self,
        value: impl Into<Bytes>,
    ) -> PositionScalarBuilder<'a, position_scalar_state::SetScalar<S>> {
        self._fields.1 = Option::Some(value.into());
        PositionScalarBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> PositionScalarBuilder<'a, S>
where
    S: position_scalar_state::State,
    S::DeckPosition: position_scalar_state::IsSet,
    S::Scalar: position_scalar_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> PositionScalar<'a> {
        PositionScalar {
            deck_position: self._fields.0.unwrap(),
            scalar: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<jacquard_common::deps::smol_str::SmolStr, Data<'a>>,
    ) -> PositionScalar<'a> {
        PositionScalar {
            deck_position: self._fields.0.unwrap(),
            scalar: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}