// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: re.cardco.poker.shuffleDeck
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use std::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_common::deps::bytes::Bytes;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// Encrypt all cards with shuffle key and permute. Each player creates one, in seat order.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", rename = "re.cardco.poker.shuffleDeck", tag = "$type")]
pub struct ShuffleDeck<'a> {
    pub created_at: Datetime,
    ///52 encrypted Ristretto255 points, base64-encoded.
    pub deck: Vec<Bytes>,
    #[serde(borrow)]
    pub table: Data<'a>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ShuffleDeckGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: ShuffleDeck<'a>,
}

impl<'a> ShuffleDeck<'a> {
    pub fn uri(
        uri: impl Into<CowStr<'a>>,
    ) -> Result<RecordUri<'a, ShuffleDeckRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct ShuffleDeckRecord;
impl XrpcResp for ShuffleDeckRecord {
    const NSID: &'static str = "re.cardco.poker.shuffleDeck";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ShuffleDeckGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<ShuffleDeckGetRecordOutput<'_>> for ShuffleDeck<'_> {
    fn from(output: ShuffleDeckGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for ShuffleDeck<'_> {
    const NSID: &'static str = "re.cardco.poker.shuffleDeck";
    type Record = ShuffleDeckRecord;
}

impl Collection for ShuffleDeckRecord {
    const NSID: &'static str = "re.cardco.poker.shuffleDeck";
    type Record = ShuffleDeckRecord;
}

impl<'a> LexiconSchema for ShuffleDeck<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.shuffleDeck"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_shuffleDeck()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.deck;
            #[allow(unused_comparisons)]
            if value.len() > 52usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("deck"),
                    max: 52usize,
                    actual: value.len(),
                });
            }
        }
        {
            let value = &self.deck;
            #[allow(unused_comparisons)]
            if value.len() < 52usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("deck"),
                    min: 52usize,
                    actual: value.len(),
                });
            }
        }
        Ok(())
    }
}

pub mod shuffle_deck_state {

    pub use crate::lexicon::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Table;
        type CreatedAt;
        type Deck;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Table = Unset;
        type CreatedAt = Unset;
        type Deck = Unset;
    }
    ///State transition - sets the `table` field to Set
    pub struct SetTable<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTable<S> {}
    impl<S: State> State for SetTable<S> {
        type Table = Set<members::table>;
        type CreatedAt = S::CreatedAt;
        type Deck = S::Deck;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Table = S::Table;
        type CreatedAt = Set<members::created_at>;
        type Deck = S::Deck;
    }
    ///State transition - sets the `deck` field to Set
    pub struct SetDeck<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDeck<S> {}
    impl<S: State> State for SetDeck<S> {
        type Table = S::Table;
        type CreatedAt = S::CreatedAt;
        type Deck = Set<members::deck>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `table` field
        pub struct table(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `deck` field
        pub struct deck(());
    }
}

/// Builder for constructing an instance of this type
pub struct ShuffleDeckBuilder<'a, S: shuffle_deck_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Datetime>, Option<Vec<Bytes>>, Option<Data<'a>>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> ShuffleDeck<'a> {
    /// Create a new builder for this type
    pub fn new() -> ShuffleDeckBuilder<'a, shuffle_deck_state::Empty> {
        ShuffleDeckBuilder::new()
    }
}

impl<'a> ShuffleDeckBuilder<'a, shuffle_deck_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ShuffleDeckBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ShuffleDeckBuilder<'a, S>
where
    S: shuffle_deck_state::State,
    S::CreatedAt: shuffle_deck_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> ShuffleDeckBuilder<'a, shuffle_deck_state::SetCreatedAt<S>> {
        self._fields.0 = Option::Some(value.into());
        ShuffleDeckBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ShuffleDeckBuilder<'a, S>
where
    S: shuffle_deck_state::State,
    S::Deck: shuffle_deck_state::IsUnset,
{
    /// Set the `deck` field (required)
    pub fn deck(
        mut self,
        value: impl Into<Vec<Bytes>>,
    ) -> ShuffleDeckBuilder<'a, shuffle_deck_state::SetDeck<S>> {
        self._fields.1 = Option::Some(value.into());
        ShuffleDeckBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ShuffleDeckBuilder<'a, S>
where
    S: shuffle_deck_state::State,
    S::Table: shuffle_deck_state::IsUnset,
{
    /// Set the `table` field (required)
    pub fn table(
        mut self,
        value: impl Into<Data<'a>>,
    ) -> ShuffleDeckBuilder<'a, shuffle_deck_state::SetTable<S>> {
        self._fields.2 = Option::Some(value.into());
        ShuffleDeckBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ShuffleDeckBuilder<'a, S>
where
    S: shuffle_deck_state::State,
    S::Table: shuffle_deck_state::IsSet,
    S::CreatedAt: shuffle_deck_state::IsSet,
    S::Deck: shuffle_deck_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> ShuffleDeck<'a> {
        ShuffleDeck {
            created_at: self._fields.0.unwrap(),
            deck: self._fields.1.unwrap(),
            table: self._fields.2.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<jacquard_common::deps::smol_str::SmolStr, Data<'a>>,
    ) -> ShuffleDeck<'a> {
        ShuffleDeck {
            created_at: self._fields.0.unwrap(),
            deck: self._fields.1.unwrap(),
            table: self._fields.2.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_re_cardco_poker_shuffleDeck() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use std::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("re.cardco.poker.shuffleDeck"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Encrypt all cards with shuffle key and permute. Each player creates one, in seat order.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("table"), SmolStr::new_static("deck"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("deck"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "52 encrypted Ristretto255 points, base64-encoded.",
                                        ),
                                    ),
                                    items: LexArrayItem::Bytes(LexBytes {
                                        ..Default::default()
                                    }),
                                    min_length: Some(52usize),
                                    max_length: Some(52usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("table"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}