// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: re.cardco.poker.table
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use std::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{Did, AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// Establishes a poker table. First record in any hand. All players must agree on this before the hand begins.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", rename = "re.cardco.poker.table", tag = "$type")]
pub struct Table<'a> {
    pub created_at: Datetime,
    ///Player DIDs in seat order.
    #[serde(borrow)]
    pub players: Vec<Did<'a>>,
    ///Small blind amount. Big blind is 2x.
    pub small_blind: i64,
    ///Starting chip count for each player.
    pub starting_chips: i64,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct TableGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: Table<'a>,
}

impl<'a> Table<'a> {
    pub fn uri(
        uri: impl Into<CowStr<'a>>,
    ) -> Result<RecordUri<'a, TableRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct TableRecord;
impl XrpcResp for TableRecord {
    const NSID: &'static str = "re.cardco.poker.table";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = TableGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<TableGetRecordOutput<'_>> for Table<'_> {
    fn from(output: TableGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for Table<'_> {
    const NSID: &'static str = "re.cardco.poker.table";
    type Record = TableRecord;
}

impl Collection for TableRecord {
    const NSID: &'static str = "re.cardco.poker.table";
    type Record = TableRecord;
}

impl<'a> LexiconSchema for Table<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.table"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_table()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.players;
            #[allow(unused_comparisons)]
            if value.len() > 10usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("players"),
                    max: 10usize,
                    actual: value.len(),
                });
            }
        }
        {
            let value = &self.players;
            #[allow(unused_comparisons)]
            if value.len() < 2usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("players"),
                    min: 2usize,
                    actual: value.len(),
                });
            }
        }
        {
            let value = &self.small_blind;
            if *value < 1i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("small_blind"),
                    min: 1i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.starting_chips;
            if *value < 1i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("starting_chips"),
                    min: 1i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod table_state {

    pub use crate::lexicon::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type StartingChips;
        type SmallBlind;
        type Players;
        type CreatedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type StartingChips = Unset;
        type SmallBlind = Unset;
        type Players = Unset;
        type CreatedAt = Unset;
    }
    ///State transition - sets the `starting_chips` field to Set
    pub struct SetStartingChips<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetStartingChips<S> {}
    impl<S: State> State for SetStartingChips<S> {
        type StartingChips = Set<members::starting_chips>;
        type SmallBlind = S::SmallBlind;
        type Players = S::Players;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `small_blind` field to Set
    pub struct SetSmallBlind<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSmallBlind<S> {}
    impl<S: State> State for SetSmallBlind<S> {
        type StartingChips = S::StartingChips;
        type SmallBlind = Set<members::small_blind>;
        type Players = S::Players;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `players` field to Set
    pub struct SetPlayers<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetPlayers<S> {}
    impl<S: State> State for SetPlayers<S> {
        type StartingChips = S::StartingChips;
        type SmallBlind = S::SmallBlind;
        type Players = Set<members::players>;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type StartingChips = S::StartingChips;
        type SmallBlind = S::SmallBlind;
        type Players = S::Players;
        type CreatedAt = Set<members::created_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `starting_chips` field
        pub struct starting_chips(());
        ///Marker type for the `small_blind` field
        pub struct small_blind(());
        ///Marker type for the `players` field
        pub struct players(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
    }
}

/// Builder for constructing an instance of this type
pub struct TableBuilder<'a, S: table_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Datetime>, Option<Vec<Did<'a>>>, Option<i64>, Option<i64>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Table<'a> {
    /// Create a new builder for this type
    pub fn new() -> TableBuilder<'a, table_state::Empty> {
        TableBuilder::new()
    }
}

impl<'a> TableBuilder<'a, table_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        TableBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TableBuilder<'a, S>
where
    S: table_state::State,
    S::CreatedAt: table_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> TableBuilder<'a, table_state::SetCreatedAt<S>> {
        self._fields.0 = Option::Some(value.into());
        TableBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TableBuilder<'a, S>
where
    S: table_state::State,
    S::Players: table_state::IsUnset,
{
    /// Set the `players` field (required)
    pub fn players(
        mut self,
        value: impl Into<Vec<Did<'a>>>,
    ) -> TableBuilder<'a, table_state::SetPlayers<S>> {
        self._fields.1 = Option::Some(value.into());
        TableBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TableBuilder<'a, S>
where
    S: table_state::State,
    S::SmallBlind: table_state::IsUnset,
{
    /// Set the `smallBlind` field (required)
    pub fn small_blind(
        mut self,
        value: impl Into<i64>,
    ) -> TableBuilder<'a, table_state::SetSmallBlind<S>> {
        self._fields.2 = Option::Some(value.into());
        TableBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TableBuilder<'a, S>
where
    S: table_state::State,
    S::StartingChips: table_state::IsUnset,
{
    /// Set the `startingChips` field (required)
    pub fn starting_chips(
        mut self,
        value: impl Into<i64>,
    ) -> TableBuilder<'a, table_state::SetStartingChips<S>> {
        self._fields.3 = Option::Some(value.into());
        TableBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TableBuilder<'a, S>
where
    S: table_state::State,
    S::StartingChips: table_state::IsSet,
    S::SmallBlind: table_state::IsSet,
    S::Players: table_state::IsSet,
    S::CreatedAt: table_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Table<'a> {
        Table {
            created_at: self._fields.0.unwrap(),
            players: self._fields.1.unwrap(),
            small_blind: self._fields.2.unwrap(),
            starting_chips: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Table<'a> {
        Table {
            created_at: self._fields.0.unwrap(),
            players: self._fields.1.unwrap(),
            small_blind: self._fields.2.unwrap(),
            starting_chips: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_re_cardco_poker_table() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use std::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("re.cardco.poker.table"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Establishes a poker table. First record in any hand. All players must agree on this before the hand begins.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("players"),
                                SmolStr::new_static("startingChips"),
                                SmolStr::new_static("smallBlind"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("players"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static("Player DIDs in seat order."),
                                    ),
                                    items: LexArrayItem::String(LexString {
                                        format: Some(LexStringFormat::Did),
                                        ..Default::default()
                                    }),
                                    min_length: Some(2usize),
                                    max_length: Some(10usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("smallBlind"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(1i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("startingChips"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(1i64),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}