// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: re.cardco.poker.verifySeed
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use std::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_common::deps::bytes::Bytes;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// Reveal the secret seed after the hand for full game replay and verification.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", rename = "re.cardco.poker.verifySeed", tag = "$type")]
pub struct VerifySeed<'a> {
    pub created_at: Datetime,
    ///The secret seed. BLAKE2b hash must match the earlier commitment.
    #[serde(with = "jacquard_common::serde_bytes_helper")]
    pub seed: Bytes,
    #[serde(borrow)]
    pub table: Data<'a>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct VerifySeedGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: VerifySeed<'a>,
}

impl<'a> VerifySeed<'a> {
    pub fn uri(
        uri: impl Into<CowStr<'a>>,
    ) -> Result<RecordUri<'a, VerifySeedRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct VerifySeedRecord;
impl XrpcResp for VerifySeedRecord {
    const NSID: &'static str = "re.cardco.poker.verifySeed";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = VerifySeedGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<VerifySeedGetRecordOutput<'_>> for VerifySeed<'_> {
    fn from(output: VerifySeedGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for VerifySeed<'_> {
    const NSID: &'static str = "re.cardco.poker.verifySeed";
    type Record = VerifySeedRecord;
}

impl Collection for VerifySeedRecord {
    const NSID: &'static str = "re.cardco.poker.verifySeed";
    type Record = VerifySeedRecord;
}

impl<'a> LexiconSchema for VerifySeed<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.verifySeed"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_verifySeed()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

pub mod verify_seed_state {

    pub use crate::lexicon::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Table;
        type Seed;
        type CreatedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Table = Unset;
        type Seed = Unset;
        type CreatedAt = Unset;
    }
    ///State transition - sets the `table` field to Set
    pub struct SetTable<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTable<S> {}
    impl<S: State> State for SetTable<S> {
        type Table = Set<members::table>;
        type Seed = S::Seed;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `seed` field to Set
    pub struct SetSeed<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSeed<S> {}
    impl<S: State> State for SetSeed<S> {
        type Table = S::Table;
        type Seed = Set<members::seed>;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Table = S::Table;
        type Seed = S::Seed;
        type CreatedAt = Set<members::created_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `table` field
        pub struct table(());
        ///Marker type for the `seed` field
        pub struct seed(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
    }
}

/// Builder for constructing an instance of this type
pub struct VerifySeedBuilder<'a, S: verify_seed_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Datetime>, Option<Bytes>, Option<Data<'a>>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> VerifySeed<'a> {
    /// Create a new builder for this type
    pub fn new() -> VerifySeedBuilder<'a, verify_seed_state::Empty> {
        VerifySeedBuilder::new()
    }
}

impl<'a> VerifySeedBuilder<'a, verify_seed_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        VerifySeedBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> VerifySeedBuilder<'a, S>
where
    S: verify_seed_state::State,
    S::CreatedAt: verify_seed_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> VerifySeedBuilder<'a, verify_seed_state::SetCreatedAt<S>> {
        self._fields.0 = Option::Some(value.into());
        VerifySeedBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> VerifySeedBuilder<'a, S>
where
    S: verify_seed_state::State,
    S::Seed: verify_seed_state::IsUnset,
{
    /// Set the `seed` field (required)
    pub fn seed(
        mut self,
        value: impl Into<Bytes>,
    ) -> VerifySeedBuilder<'a, verify_seed_state::SetSeed<S>> {
        self._fields.1 = Option::Some(value.into());
        VerifySeedBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> VerifySeedBuilder<'a, S>
where
    S: verify_seed_state::State,
    S::Table: verify_seed_state::IsUnset,
{
    /// Set the `table` field (required)
    pub fn table(
        mut self,
        value: impl Into<Data<'a>>,
    ) -> VerifySeedBuilder<'a, verify_seed_state::SetTable<S>> {
        self._fields.2 = Option::Some(value.into());
        VerifySeedBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> VerifySeedBuilder<'a, S>
where
    S: verify_seed_state::State,
    S::Table: verify_seed_state::IsSet,
    S::Seed: verify_seed_state::IsSet,
    S::CreatedAt: verify_seed_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> VerifySeed<'a> {
        VerifySeed {
            created_at: self._fields.0.unwrap(),
            seed: self._fields.1.unwrap(),
            table: self._fields.2.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<jacquard_common::deps::smol_str::SmolStr, Data<'a>>,
    ) -> VerifySeed<'a> {
        VerifySeed {
            created_at: self._fields.0.unwrap(),
            seed: self._fields.1.unwrap(),
            table: self._fields.2.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_re_cardco_poker_verifySeed() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use std::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("re.cardco.poker.verifySeed"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Reveal the secret seed after the hand for full game replay and verification.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("table"), SmolStr::new_static("seed"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("seed"),
                                LexObjectProperty::Bytes(LexBytes {
                                    max_length: Some(256usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("table"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}