// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: re.cardco.blackjack.defs
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

pub mod action;
pub mod table;

#[allow(unused_imports)]
use std::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_common::deps::bytes::Bytes;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// Commit a hashed seed for later verification.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct CommitSeed<'a> {
    ///BLAKE2b hash of the player's secret seed.
    #[serde(with = "jacquard_common::serde_bytes_helper")]
    pub commitment: Bytes,
}

/// A playing decision for the hand currently in turn.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct Decision<'a> {
    ///The move for the current hand.
    #[serde(borrow)]
    pub r#move: DecisionMove<'a>,
}

/// The move for the current hand.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DecisionMove<'a> {
    Hit,
    Stand,
    Double,
    Split,
    Surrender,
    Other(CowStr<'a>),
}

impl<'a> DecisionMove<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Hit => "hit",
            Self::Stand => "stand",
            Self::Double => "double",
            Self::Split => "split",
            Self::Surrender => "surrender",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for DecisionMove<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "hit" => Self::Hit,
            "stand" => Self::Stand,
            "double" => Self::Double,
            "split" => Self::Split,
            "surrender" => Self::Surrender,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for DecisionMove<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "hit" => Self::Hit,
            "stand" => Self::Stand,
            "double" => Self::Double,
            "split" => Self::Split,
            "surrender" => Self::Surrender,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for DecisionMove<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for DecisionMove<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for DecisionMove<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for DecisionMove<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for DecisionMove<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for DecisionMove<'_> {
    type Output = DecisionMove<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            DecisionMove::Hit => DecisionMove::Hit,
            DecisionMove::Stand => DecisionMove::Stand,
            DecisionMove::Double => DecisionMove::Double,
            DecisionMove::Split => DecisionMove::Split,
            DecisionMove::Surrender => DecisionMove::Surrender,
            DecisionMove::Other(v) => DecisionMove::Other(v.into_static()),
        }
    }
}

/// Take or decline insurance against a banker blackjack (offered when the banker upcard is an ace). Costs floor(wager/2); pays 2:1.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct Insurance<'a> {
    ///True to take insurance, false to decline.
    pub take: bool,
}

/// Remove shuffle encryption and apply per-position lock keys.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct LockDeck<'a> {
    ///52 locked Ristretto255 points.
    pub deck: Vec<Bytes>,
}

/// Reveal a per-position lock scalar to deal a card face-up.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct RevealLockKey<'a> {
    ///Which card position in the deck is being revealed.
    pub deck_position: i64,
    ///Ristretto255 lock decryption scalar for this position.
    #[serde(with = "jacquard_common::serde_bytes_helper")]
    pub scalar: Bytes,
}

/// Encrypt all cards with shuffle key and permute.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ShuffleDeck<'a> {
    ///52 encrypted Ristretto255 points.
    pub deck: Vec<Bytes>,
}

/// Reveal the secret seed for full game replay and verification.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct VerifySeed<'a> {
    ///The secret seed. BLAKE2b hash must match the earlier commitment.
    #[serde(with = "jacquard_common::serde_bytes_helper")]
    pub seed: Bytes,
}

/// Post the round wager (escrowed from chips immediately).

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct Wager<'a> {
    ///Chips wagered. At least min(minBet, chips), at most the player's chips.
    pub amount: i64,
}

impl<'a> LexiconSchema for CommitSeed<'a> {
    fn nsid() -> &'static str {
        "re.cardco.blackjack.defs"
    }
    fn def_name() -> &'static str {
        "commitSeed"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_blackjack_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<'a> LexiconSchema for Decision<'a> {
    fn nsid() -> &'static str {
        "re.cardco.blackjack.defs"
    }
    fn def_name() -> &'static str {
        "decision"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_blackjack_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<'a> LexiconSchema for Insurance<'a> {
    fn nsid() -> &'static str {
        "re.cardco.blackjack.defs"
    }
    fn def_name() -> &'static str {
        "insurance"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_blackjack_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<'a> LexiconSchema for LockDeck<'a> {
    fn nsid() -> &'static str {
        "re.cardco.blackjack.defs"
    }
    fn def_name() -> &'static str {
        "lockDeck"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_blackjack_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.deck;
            #[allow(unused_comparisons)]
            if value.len() > 52usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("deck"),
                    max: 52usize,
                    actual: value.len(),
                });
            }
        }
        {
            let value = &self.deck;
            #[allow(unused_comparisons)]
            if value.len() < 52usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("deck"),
                    min: 52usize,
                    actual: value.len(),
                });
            }
        }
        Ok(())
    }
}

impl<'a> LexiconSchema for RevealLockKey<'a> {
    fn nsid() -> &'static str {
        "re.cardco.blackjack.defs"
    }
    fn def_name() -> &'static str {
        "revealLockKey"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_blackjack_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.deck_position;
            if *value > 51i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("deck_position"),
                    max: 51i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.deck_position;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("deck_position"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

impl<'a> LexiconSchema for ShuffleDeck<'a> {
    fn nsid() -> &'static str {
        "re.cardco.blackjack.defs"
    }
    fn def_name() -> &'static str {
        "shuffleDeck"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_blackjack_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.deck;
            #[allow(unused_comparisons)]
            if value.len() > 52usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("deck"),
                    max: 52usize,
                    actual: value.len(),
                });
            }
        }
        {
            let value = &self.deck;
            #[allow(unused_comparisons)]
            if value.len() < 52usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("deck"),
                    min: 52usize,
                    actual: value.len(),
                });
            }
        }
        Ok(())
    }
}

impl<'a> LexiconSchema for VerifySeed<'a> {
    fn nsid() -> &'static str {
        "re.cardco.blackjack.defs"
    }
    fn def_name() -> &'static str {
        "verifySeed"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_blackjack_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<'a> LexiconSchema for Wager<'a> {
    fn nsid() -> &'static str {
        "re.cardco.blackjack.defs"
    }
    fn def_name() -> &'static str {
        "wager"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_blackjack_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.amount;
            if *value < 1i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("amount"),
                    min: 1i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod commit_seed_state {
    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Commitment;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Commitment = Unset;
    }
    ///State transition - sets the `commitment` field to Set
    pub struct SetCommitment<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCommitment<S> {}
    impl<S: State> State for SetCommitment<S> {
        type Commitment = Set<members::commitment>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `commitment` field
        pub struct commitment(());
    }
}

/// Builder for constructing an instance of this type
pub struct CommitSeedBuilder<'a, S: commit_seed_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Bytes>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> CommitSeed<'a> {
    /// Create a new builder for this type
    pub fn new() -> CommitSeedBuilder<'a, commit_seed_state::Empty> {
        CommitSeedBuilder::new()
    }
}

impl<'a> CommitSeedBuilder<'a, commit_seed_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        CommitSeedBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> CommitSeedBuilder<'a, S>
where
    S: commit_seed_state::State,
    S::Commitment: commit_seed_state::IsUnset,
{
    /// Set the `commitment` field (required)
    pub fn commitment(
        mut self,
        value: impl Into<Bytes>,
    ) -> CommitSeedBuilder<'a, commit_seed_state::SetCommitment<S>> {
        self._fields.0 = Option::Some(value.into());
        CommitSeedBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> CommitSeedBuilder<'a, S>
where
    S: commit_seed_state::State,
    S::Commitment: commit_seed_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> CommitSeed<'a> {
        CommitSeed {
            commitment: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> CommitSeed<'a> {
        CommitSeed {
            commitment: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_re_cardco_blackjack_defs() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use std::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("re.cardco.blackjack.defs"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("commitSeed"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Commit a hashed seed for later verification.",
                    )),
                    required: Some(vec![SmolStr::new_static("commitment")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("commitment"),
                            LexObjectProperty::Bytes(LexBytes {
                                max_length: Some(32usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("decision"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "A playing decision for the hand currently in turn.",
                    )),
                    required: Some(vec![SmolStr::new_static("move")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("move"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The move for the current hand.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("insurance"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "Take or decline insurance against a banker blackjack (offered when the banker upcard is an ace). Costs floor(wager/2); pays 2:1.",
                        ),
                    ),
                    required: Some(vec![SmolStr::new_static("take")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("take"),
                            LexObjectProperty::Boolean(LexBoolean {
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("lockDeck"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Remove shuffle encryption and apply per-position lock keys.",
                    )),
                    required: Some(vec![SmolStr::new_static("deck")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("deck"),
                            LexObjectProperty::Array(LexArray {
                                description: Some(CowStr::new_static(
                                    "52 locked Ristretto255 points.",
                                )),
                                items: LexArrayItem::Bytes(LexBytes {
                                    ..Default::default()
                                }),
                                min_length: Some(52usize),
                                max_length: Some(52usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("revealLockKey"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Reveal a per-position lock scalar to deal a card face-up.",
                    )),
                    required: Some(vec![
                        SmolStr::new_static("deckPosition"),
                        SmolStr::new_static("scalar"),
                    ]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("deckPosition"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                maximum: Some(51i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("scalar"),
                            LexObjectProperty::Bytes(LexBytes {
                                max_length: Some(32usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("shuffleDeck"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Encrypt all cards with shuffle key and permute.",
                    )),
                    required: Some(vec![SmolStr::new_static("deck")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("deck"),
                            LexObjectProperty::Array(LexArray {
                                description: Some(CowStr::new_static(
                                    "52 encrypted Ristretto255 points.",
                                )),
                                items: LexArrayItem::Bytes(LexBytes {
                                    ..Default::default()
                                }),
                                min_length: Some(52usize),
                                max_length: Some(52usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("verifySeed"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Reveal the secret seed for full game replay and verification.",
                    )),
                    required: Some(vec![SmolStr::new_static("seed")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("seed"),
                            LexObjectProperty::Bytes(LexBytes {
                                max_length: Some(256usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("wager"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Post the round wager (escrowed from chips immediately).",
                    )),
                    required: Some(vec![SmolStr::new_static("amount")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("amount"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(1i64),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod insurance_state {
    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Take;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Take = Unset;
    }
    ///State transition - sets the `take` field to Set
    pub struct SetTake<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTake<S> {}
    impl<S: State> State for SetTake<S> {
        type Take = Set<members::take>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `take` field
        pub struct take(());
    }
}

/// Builder for constructing an instance of this type
pub struct InsuranceBuilder<'a, S: insurance_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<bool>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Insurance<'a> {
    /// Create a new builder for this type
    pub fn new() -> InsuranceBuilder<'a, insurance_state::Empty> {
        InsuranceBuilder::new()
    }
}

impl<'a> InsuranceBuilder<'a, insurance_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        InsuranceBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> InsuranceBuilder<'a, S>
where
    S: insurance_state::State,
    S::Take: insurance_state::IsUnset,
{
    /// Set the `take` field (required)
    pub fn take(
        mut self,
        value: impl Into<bool>,
    ) -> InsuranceBuilder<'a, insurance_state::SetTake<S>> {
        self._fields.0 = Option::Some(value.into());
        InsuranceBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> InsuranceBuilder<'a, S>
where
    S: insurance_state::State,
    S::Take: insurance_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Insurance<'a> {
        Insurance {
            take: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Insurance<'a> {
        Insurance {
            take: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod lock_deck_state {
    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Deck;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Deck = Unset;
    }
    ///State transition - sets the `deck` field to Set
    pub struct SetDeck<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDeck<S> {}
    impl<S: State> State for SetDeck<S> {
        type Deck = Set<members::deck>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `deck` field
        pub struct deck(());
    }
}

/// Builder for constructing an instance of this type
pub struct LockDeckBuilder<'a, S: lock_deck_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Vec<Bytes>>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> LockDeck<'a> {
    /// Create a new builder for this type
    pub fn new() -> LockDeckBuilder<'a, lock_deck_state::Empty> {
        LockDeckBuilder::new()
    }
}

impl<'a> LockDeckBuilder<'a, lock_deck_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        LockDeckBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> LockDeckBuilder<'a, S>
where
    S: lock_deck_state::State,
    S::Deck: lock_deck_state::IsUnset,
{
    /// Set the `deck` field (required)
    pub fn deck(
        mut self,
        value: impl Into<Vec<Bytes>>,
    ) -> LockDeckBuilder<'a, lock_deck_state::SetDeck<S>> {
        self._fields.0 = Option::Some(value.into());
        LockDeckBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> LockDeckBuilder<'a, S>
where
    S: lock_deck_state::State,
    S::Deck: lock_deck_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> LockDeck<'a> {
        LockDeck {
            deck: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> LockDeck<'a> {
        LockDeck {
            deck: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod reveal_lock_key_state {
    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Scalar;
        type DeckPosition;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Scalar = Unset;
        type DeckPosition = Unset;
    }
    ///State transition - sets the `scalar` field to Set
    pub struct SetScalar<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetScalar<S> {}
    impl<S: State> State for SetScalar<S> {
        type Scalar = Set<members::scalar>;
        type DeckPosition = S::DeckPosition;
    }
    ///State transition - sets the `deck_position` field to Set
    pub struct SetDeckPosition<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDeckPosition<S> {}
    impl<S: State> State for SetDeckPosition<S> {
        type Scalar = S::Scalar;
        type DeckPosition = Set<members::deck_position>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `scalar` field
        pub struct scalar(());
        ///Marker type for the `deck_position` field
        pub struct deck_position(());
    }
}

/// Builder for constructing an instance of this type
pub struct RevealLockKeyBuilder<'a, S: reveal_lock_key_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<i64>, Option<Bytes>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> RevealLockKey<'a> {
    /// Create a new builder for this type
    pub fn new() -> RevealLockKeyBuilder<'a, reveal_lock_key_state::Empty> {
        RevealLockKeyBuilder::new()
    }
}

impl<'a> RevealLockKeyBuilder<'a, reveal_lock_key_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        RevealLockKeyBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealLockKeyBuilder<'a, S>
where
    S: reveal_lock_key_state::State,
    S::DeckPosition: reveal_lock_key_state::IsUnset,
{
    /// Set the `deckPosition` field (required)
    pub fn deck_position(
        mut self,
        value: impl Into<i64>,
    ) -> RevealLockKeyBuilder<'a, reveal_lock_key_state::SetDeckPosition<S>> {
        self._fields.0 = Option::Some(value.into());
        RevealLockKeyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealLockKeyBuilder<'a, S>
where
    S: reveal_lock_key_state::State,
    S::Scalar: reveal_lock_key_state::IsUnset,
{
    /// Set the `scalar` field (required)
    pub fn scalar(
        mut self,
        value: impl Into<Bytes>,
    ) -> RevealLockKeyBuilder<'a, reveal_lock_key_state::SetScalar<S>> {
        self._fields.1 = Option::Some(value.into());
        RevealLockKeyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealLockKeyBuilder<'a, S>
where
    S: reveal_lock_key_state::State,
    S::Scalar: reveal_lock_key_state::IsSet,
    S::DeckPosition: reveal_lock_key_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> RevealLockKey<'a> {
        RevealLockKey {
            deck_position: self._fields.0.unwrap(),
            scalar: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> RevealLockKey<'a> {
        RevealLockKey {
            deck_position: self._fields.0.unwrap(),
            scalar: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod shuffle_deck_state {
    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Deck;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Deck = Unset;
    }
    ///State transition - sets the `deck` field to Set
    pub struct SetDeck<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDeck<S> {}
    impl<S: State> State for SetDeck<S> {
        type Deck = Set<members::deck>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `deck` field
        pub struct deck(());
    }
}

/// Builder for constructing an instance of this type
pub struct ShuffleDeckBuilder<'a, S: shuffle_deck_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Vec<Bytes>>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> ShuffleDeck<'a> {
    /// Create a new builder for this type
    pub fn new() -> ShuffleDeckBuilder<'a, shuffle_deck_state::Empty> {
        ShuffleDeckBuilder::new()
    }
}

impl<'a> ShuffleDeckBuilder<'a, shuffle_deck_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ShuffleDeckBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ShuffleDeckBuilder<'a, S>
where
    S: shuffle_deck_state::State,
    S::Deck: shuffle_deck_state::IsUnset,
{
    /// Set the `deck` field (required)
    pub fn deck(
        mut self,
        value: impl Into<Vec<Bytes>>,
    ) -> ShuffleDeckBuilder<'a, shuffle_deck_state::SetDeck<S>> {
        self._fields.0 = Option::Some(value.into());
        ShuffleDeckBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ShuffleDeckBuilder<'a, S>
where
    S: shuffle_deck_state::State,
    S::Deck: shuffle_deck_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> ShuffleDeck<'a> {
        ShuffleDeck {
            deck: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> ShuffleDeck<'a> {
        ShuffleDeck {
            deck: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod verify_seed_state {
    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Seed;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Seed = Unset;
    }
    ///State transition - sets the `seed` field to Set
    pub struct SetSeed<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSeed<S> {}
    impl<S: State> State for SetSeed<S> {
        type Seed = Set<members::seed>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `seed` field
        pub struct seed(());
    }
}

/// Builder for constructing an instance of this type
pub struct VerifySeedBuilder<'a, S: verify_seed_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Bytes>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> VerifySeed<'a> {
    /// Create a new builder for this type
    pub fn new() -> VerifySeedBuilder<'a, verify_seed_state::Empty> {
        VerifySeedBuilder::new()
    }
}

impl<'a> VerifySeedBuilder<'a, verify_seed_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        VerifySeedBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> VerifySeedBuilder<'a, S>
where
    S: verify_seed_state::State,
    S::Seed: verify_seed_state::IsUnset,
{
    /// Set the `seed` field (required)
    pub fn seed(
        mut self,
        value: impl Into<Bytes>,
    ) -> VerifySeedBuilder<'a, verify_seed_state::SetSeed<S>> {
        self._fields.0 = Option::Some(value.into());
        VerifySeedBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> VerifySeedBuilder<'a, S>
where
    S: verify_seed_state::State,
    S::Seed: verify_seed_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> VerifySeed<'a> {
        VerifySeed {
            seed: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> VerifySeed<'a> {
        VerifySeed {
            seed: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod wager_state {
    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Amount;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Amount = Unset;
    }
    ///State transition - sets the `amount` field to Set
    pub struct SetAmount<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetAmount<S> {}
    impl<S: State> State for SetAmount<S> {
        type Amount = Set<members::amount>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `amount` field
        pub struct amount(());
    }
}

/// Builder for constructing an instance of this type
pub struct WagerBuilder<'a, S: wager_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<i64>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Wager<'a> {
    /// Create a new builder for this type
    pub fn new() -> WagerBuilder<'a, wager_state::Empty> {
        WagerBuilder::new()
    }
}

impl<'a> WagerBuilder<'a, wager_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        WagerBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> WagerBuilder<'a, S>
where
    S: wager_state::State,
    S::Amount: wager_state::IsUnset,
{
    /// Set the `amount` field (required)
    pub fn amount(mut self, value: impl Into<i64>) -> WagerBuilder<'a, wager_state::SetAmount<S>> {
        self._fields.0 = Option::Some(value.into());
        WagerBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> WagerBuilder<'a, S>
where
    S: wager_state::State,
    S::Amount: wager_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Wager<'a> {
        Wager {
            amount: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Wager<'a> {
        Wager {
            amount: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}
