// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: re.cardco.poker.defs
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

pub mod action;
pub mod table;

#[allow(unused_imports)]
use std::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_common::deps::bytes::Bytes;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::lexicon::re_cardco::poker;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// A betting action.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct Bet<'a> {
    ///The betting action. For raises, use 'raise' with the amount field.
    #[serde(borrow)]
    pub action: BetAction<'a>,
    ///Raise amount (total, not incremental). Only present for raises.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<i64>,
}

/// The betting action. For raises, use 'raise' with the amount field.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum BetAction<'a> {
    Fold,
    Check,
    Call,
    AllIn,
    Other(CowStr<'a>),
}

impl<'a> BetAction<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Fold => "fold",
            Self::Check => "check",
            Self::Call => "call",
            Self::AllIn => "allIn",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for BetAction<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "fold" => Self::Fold,
            "check" => Self::Check,
            "call" => Self::Call,
            "allIn" => Self::AllIn,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for BetAction<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "fold" => Self::Fold,
            "check" => Self::Check,
            "call" => Self::Call,
            "allIn" => Self::AllIn,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for BetAction<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for BetAction<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for BetAction<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for BetAction<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for BetAction<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for BetAction<'_> {
    type Output = BetAction<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            BetAction::Fold => BetAction::Fold,
            BetAction::Check => BetAction::Check,
            BetAction::Call => BetAction::Call,
            BetAction::AllIn => BetAction::AllIn,
            BetAction::Other(v) => BetAction::Other(v.into_static()),
        }
    }
}

/// Commit a hashed seed for later verification.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct CommitSeed<'a> {
    ///BLAKE2b hash of the player's secret seed.
    #[serde(with = "jacquard_common::serde_bytes_helper")]
    pub commitment: Bytes,
}

/// Remove shuffle encryption and apply per-position lock keys.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct LockDeck<'a> {
    ///52 locked Ristretto255 points.
    pub deck: Vec<Bytes>,
}

/// A deck position and its associated lock decryption scalar.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct PositionScalar<'a> {
    pub deck_position: i64,
    ///Ristretto255 lock decryption scalar.
    #[serde(with = "jacquard_common::serde_bytes_helper")]
    pub scalar: Bytes,
}

/// Reveal hole card lock keys at showdown.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct RevealHand<'a> {
    ///Lock key reveals for hole card positions.
    #[serde(borrow)]
    pub reveals: Vec<poker::PositionScalar<'a>>,
}

/// Reveal a per-position lock scalar to deal a card.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct RevealLockKey<'a> {
    ///Which card position in the deck is being revealed.
    pub deck_position: i64,
    ///Ristretto255 lock decryption scalar for this position.
    #[serde(with = "jacquard_common::serde_bytes_helper")]
    pub scalar: Bytes,
}

/// Encrypt all cards with shuffle key and permute.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ShuffleDeck<'a> {
    ///52 encrypted Ristretto255 points.
    pub deck: Vec<Bytes>,
}

/// Reveal the secret seed for full game replay and verification.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct VerifySeed<'a> {
    ///The secret seed. BLAKE2b hash must match the earlier commitment.
    #[serde(with = "jacquard_common::serde_bytes_helper")]
    pub seed: Bytes,
}

impl<'a> LexiconSchema for Bet<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.defs"
    }
    fn def_name() -> &'static str {
        "bet"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.amount {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("amount"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

impl<'a> LexiconSchema for CommitSeed<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.defs"
    }
    fn def_name() -> &'static str {
        "commitSeed"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<'a> LexiconSchema for LockDeck<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.defs"
    }
    fn def_name() -> &'static str {
        "lockDeck"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.deck;
            #[allow(unused_comparisons)]
            if value.len() > 52usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("deck"),
                    max: 52usize,
                    actual: value.len(),
                });
            }
        }
        {
            let value = &self.deck;
            #[allow(unused_comparisons)]
            if value.len() < 52usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("deck"),
                    min: 52usize,
                    actual: value.len(),
                });
            }
        }
        Ok(())
    }
}

impl<'a> LexiconSchema for PositionScalar<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.defs"
    }
    fn def_name() -> &'static str {
        "positionScalar"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.deck_position;
            if *value > 51i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("deck_position"),
                    max: 51i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.deck_position;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("deck_position"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

impl<'a> LexiconSchema for RevealHand<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.defs"
    }
    fn def_name() -> &'static str {
        "revealHand"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<'a> LexiconSchema for RevealLockKey<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.defs"
    }
    fn def_name() -> &'static str {
        "revealLockKey"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.deck_position;
            if *value > 51i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("deck_position"),
                    max: 51i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.deck_position;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("deck_position"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

impl<'a> LexiconSchema for ShuffleDeck<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.defs"
    }
    fn def_name() -> &'static str {
        "shuffleDeck"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.deck;
            #[allow(unused_comparisons)]
            if value.len() > 52usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("deck"),
                    max: 52usize,
                    actual: value.len(),
                });
            }
        }
        {
            let value = &self.deck;
            #[allow(unused_comparisons)]
            if value.len() < 52usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("deck"),
                    min: 52usize,
                    actual: value.len(),
                });
            }
        }
        Ok(())
    }
}

impl<'a> LexiconSchema for VerifySeed<'a> {
    fn nsid() -> &'static str {
        "re.cardco.poker.defs"
    }
    fn def_name() -> &'static str {
        "verifySeed"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_re_cardco_poker_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

fn lexicon_doc_re_cardco_poker_defs() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use std::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("re.cardco.poker.defs"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("bet"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static("A betting action.")),
                    required: Some(vec![SmolStr::new_static("action")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("action"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "The betting action. For raises, use 'raise' with the amount field.",
                                    ),
                                ),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("amount"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("commitSeed"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Commit a hashed seed for later verification.",
                    )),
                    required: Some(vec![SmolStr::new_static("commitment")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("commitment"),
                            LexObjectProperty::Bytes(LexBytes {
                                max_length: Some(32usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("lockDeck"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Remove shuffle encryption and apply per-position lock keys.",
                    )),
                    required: Some(vec![SmolStr::new_static("deck")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("deck"),
                            LexObjectProperty::Array(LexArray {
                                description: Some(CowStr::new_static(
                                    "52 locked Ristretto255 points.",
                                )),
                                items: LexArrayItem::Bytes(LexBytes {
                                    ..Default::default()
                                }),
                                min_length: Some(52usize),
                                max_length: Some(52usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("positionScalar"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "A deck position and its associated lock decryption scalar.",
                    )),
                    required: Some(vec![
                        SmolStr::new_static("deckPosition"),
                        SmolStr::new_static("scalar"),
                    ]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("deckPosition"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                maximum: Some(51i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("scalar"),
                            LexObjectProperty::Bytes(LexBytes {
                                max_length: Some(32usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("revealHand"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Reveal hole card lock keys at showdown.",
                    )),
                    required: Some(vec![SmolStr::new_static("reveals")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("reveals"),
                            LexObjectProperty::Array(LexArray {
                                description: Some(CowStr::new_static(
                                    "Lock key reveals for hole card positions.",
                                )),
                                items: LexArrayItem::Ref(LexRef {
                                    r#ref: CowStr::new_static("#positionScalar"),
                                    ..Default::default()
                                }),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("revealLockKey"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Reveal a per-position lock scalar to deal a card.",
                    )),
                    required: Some(vec![
                        SmolStr::new_static("deckPosition"),
                        SmolStr::new_static("scalar"),
                    ]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("deckPosition"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                maximum: Some(51i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("scalar"),
                            LexObjectProperty::Bytes(LexBytes {
                                max_length: Some(32usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("shuffleDeck"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Encrypt all cards with shuffle key and permute.",
                    )),
                    required: Some(vec![SmolStr::new_static("deck")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("deck"),
                            LexObjectProperty::Array(LexArray {
                                description: Some(CowStr::new_static(
                                    "52 encrypted Ristretto255 points.",
                                )),
                                items: LexArrayItem::Bytes(LexBytes {
                                    ..Default::default()
                                }),
                                min_length: Some(52usize),
                                max_length: Some(52usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("verifySeed"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Reveal the secret seed for full game replay and verification.",
                    )),
                    required: Some(vec![SmolStr::new_static("seed")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("seed"),
                            LexObjectProperty::Bytes(LexBytes {
                                max_length: Some(256usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod commit_seed_state {

    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Commitment;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Commitment = Unset;
    }
    ///State transition - sets the `commitment` field to Set
    pub struct SetCommitment<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCommitment<S> {}
    impl<S: State> State for SetCommitment<S> {
        type Commitment = Set<members::commitment>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `commitment` field
        pub struct commitment(());
    }
}

/// Builder for constructing an instance of this type
pub struct CommitSeedBuilder<'a, S: commit_seed_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Bytes>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> CommitSeed<'a> {
    /// Create a new builder for this type
    pub fn new() -> CommitSeedBuilder<'a, commit_seed_state::Empty> {
        CommitSeedBuilder::new()
    }
}

impl<'a> CommitSeedBuilder<'a, commit_seed_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        CommitSeedBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> CommitSeedBuilder<'a, S>
where
    S: commit_seed_state::State,
    S::Commitment: commit_seed_state::IsUnset,
{
    /// Set the `commitment` field (required)
    pub fn commitment(
        mut self,
        value: impl Into<Bytes>,
    ) -> CommitSeedBuilder<'a, commit_seed_state::SetCommitment<S>> {
        self._fields.0 = Option::Some(value.into());
        CommitSeedBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> CommitSeedBuilder<'a, S>
where
    S: commit_seed_state::State,
    S::Commitment: commit_seed_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> CommitSeed<'a> {
        CommitSeed {
            commitment: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> CommitSeed<'a> {
        CommitSeed {
            commitment: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod lock_deck_state {

    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Deck;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Deck = Unset;
    }
    ///State transition - sets the `deck` field to Set
    pub struct SetDeck<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDeck<S> {}
    impl<S: State> State for SetDeck<S> {
        type Deck = Set<members::deck>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `deck` field
        pub struct deck(());
    }
}

/// Builder for constructing an instance of this type
pub struct LockDeckBuilder<'a, S: lock_deck_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Vec<Bytes>>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> LockDeck<'a> {
    /// Create a new builder for this type
    pub fn new() -> LockDeckBuilder<'a, lock_deck_state::Empty> {
        LockDeckBuilder::new()
    }
}

impl<'a> LockDeckBuilder<'a, lock_deck_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        LockDeckBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> LockDeckBuilder<'a, S>
where
    S: lock_deck_state::State,
    S::Deck: lock_deck_state::IsUnset,
{
    /// Set the `deck` field (required)
    pub fn deck(
        mut self,
        value: impl Into<Vec<Bytes>>,
    ) -> LockDeckBuilder<'a, lock_deck_state::SetDeck<S>> {
        self._fields.0 = Option::Some(value.into());
        LockDeckBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> LockDeckBuilder<'a, S>
where
    S: lock_deck_state::State,
    S::Deck: lock_deck_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> LockDeck<'a> {
        LockDeck {
            deck: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> LockDeck<'a> {
        LockDeck {
            deck: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod position_scalar_state {

    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type DeckPosition;
        type Scalar;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type DeckPosition = Unset;
        type Scalar = Unset;
    }
    ///State transition - sets the `deck_position` field to Set
    pub struct SetDeckPosition<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDeckPosition<S> {}
    impl<S: State> State for SetDeckPosition<S> {
        type DeckPosition = Set<members::deck_position>;
        type Scalar = S::Scalar;
    }
    ///State transition - sets the `scalar` field to Set
    pub struct SetScalar<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetScalar<S> {}
    impl<S: State> State for SetScalar<S> {
        type DeckPosition = S::DeckPosition;
        type Scalar = Set<members::scalar>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `deck_position` field
        pub struct deck_position(());
        ///Marker type for the `scalar` field
        pub struct scalar(());
    }
}

/// Builder for constructing an instance of this type
pub struct PositionScalarBuilder<'a, S: position_scalar_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<i64>, Option<Bytes>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> PositionScalar<'a> {
    /// Create a new builder for this type
    pub fn new() -> PositionScalarBuilder<'a, position_scalar_state::Empty> {
        PositionScalarBuilder::new()
    }
}

impl<'a> PositionScalarBuilder<'a, position_scalar_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        PositionScalarBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> PositionScalarBuilder<'a, S>
where
    S: position_scalar_state::State,
    S::DeckPosition: position_scalar_state::IsUnset,
{
    /// Set the `deckPosition` field (required)
    pub fn deck_position(
        mut self,
        value: impl Into<i64>,
    ) -> PositionScalarBuilder<'a, position_scalar_state::SetDeckPosition<S>> {
        self._fields.0 = Option::Some(value.into());
        PositionScalarBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> PositionScalarBuilder<'a, S>
where
    S: position_scalar_state::State,
    S::Scalar: position_scalar_state::IsUnset,
{
    /// Set the `scalar` field (required)
    pub fn scalar(
        mut self,
        value: impl Into<Bytes>,
    ) -> PositionScalarBuilder<'a, position_scalar_state::SetScalar<S>> {
        self._fields.1 = Option::Some(value.into());
        PositionScalarBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> PositionScalarBuilder<'a, S>
where
    S: position_scalar_state::State,
    S::DeckPosition: position_scalar_state::IsSet,
    S::Scalar: position_scalar_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> PositionScalar<'a> {
        PositionScalar {
            deck_position: self._fields.0.unwrap(),
            scalar: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> PositionScalar<'a> {
        PositionScalar {
            deck_position: self._fields.0.unwrap(),
            scalar: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod reveal_hand_state {

    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Reveals;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Reveals = Unset;
    }
    ///State transition - sets the `reveals` field to Set
    pub struct SetReveals<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetReveals<S> {}
    impl<S: State> State for SetReveals<S> {
        type Reveals = Set<members::reveals>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `reveals` field
        pub struct reveals(());
    }
}

/// Builder for constructing an instance of this type
pub struct RevealHandBuilder<'a, S: reveal_hand_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Vec<poker::PositionScalar<'a>>>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> RevealHand<'a> {
    /// Create a new builder for this type
    pub fn new() -> RevealHandBuilder<'a, reveal_hand_state::Empty> {
        RevealHandBuilder::new()
    }
}

impl<'a> RevealHandBuilder<'a, reveal_hand_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        RevealHandBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealHandBuilder<'a, S>
where
    S: reveal_hand_state::State,
    S::Reveals: reveal_hand_state::IsUnset,
{
    /// Set the `reveals` field (required)
    pub fn reveals(
        mut self,
        value: impl Into<Vec<poker::PositionScalar<'a>>>,
    ) -> RevealHandBuilder<'a, reveal_hand_state::SetReveals<S>> {
        self._fields.0 = Option::Some(value.into());
        RevealHandBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealHandBuilder<'a, S>
where
    S: reveal_hand_state::State,
    S::Reveals: reveal_hand_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> RevealHand<'a> {
        RevealHand {
            reveals: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> RevealHand<'a> {
        RevealHand {
            reveals: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod reveal_lock_key_state {

    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type DeckPosition;
        type Scalar;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type DeckPosition = Unset;
        type Scalar = Unset;
    }
    ///State transition - sets the `deck_position` field to Set
    pub struct SetDeckPosition<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDeckPosition<S> {}
    impl<S: State> State for SetDeckPosition<S> {
        type DeckPosition = Set<members::deck_position>;
        type Scalar = S::Scalar;
    }
    ///State transition - sets the `scalar` field to Set
    pub struct SetScalar<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetScalar<S> {}
    impl<S: State> State for SetScalar<S> {
        type DeckPosition = S::DeckPosition;
        type Scalar = Set<members::scalar>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `deck_position` field
        pub struct deck_position(());
        ///Marker type for the `scalar` field
        pub struct scalar(());
    }
}

/// Builder for constructing an instance of this type
pub struct RevealLockKeyBuilder<'a, S: reveal_lock_key_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<i64>, Option<Bytes>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> RevealLockKey<'a> {
    /// Create a new builder for this type
    pub fn new() -> RevealLockKeyBuilder<'a, reveal_lock_key_state::Empty> {
        RevealLockKeyBuilder::new()
    }
}

impl<'a> RevealLockKeyBuilder<'a, reveal_lock_key_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        RevealLockKeyBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealLockKeyBuilder<'a, S>
where
    S: reveal_lock_key_state::State,
    S::DeckPosition: reveal_lock_key_state::IsUnset,
{
    /// Set the `deckPosition` field (required)
    pub fn deck_position(
        mut self,
        value: impl Into<i64>,
    ) -> RevealLockKeyBuilder<'a, reveal_lock_key_state::SetDeckPosition<S>> {
        self._fields.0 = Option::Some(value.into());
        RevealLockKeyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealLockKeyBuilder<'a, S>
where
    S: reveal_lock_key_state::State,
    S::Scalar: reveal_lock_key_state::IsUnset,
{
    /// Set the `scalar` field (required)
    pub fn scalar(
        mut self,
        value: impl Into<Bytes>,
    ) -> RevealLockKeyBuilder<'a, reveal_lock_key_state::SetScalar<S>> {
        self._fields.1 = Option::Some(value.into());
        RevealLockKeyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RevealLockKeyBuilder<'a, S>
where
    S: reveal_lock_key_state::State,
    S::DeckPosition: reveal_lock_key_state::IsSet,
    S::Scalar: reveal_lock_key_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> RevealLockKey<'a> {
        RevealLockKey {
            deck_position: self._fields.0.unwrap(),
            scalar: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> RevealLockKey<'a> {
        RevealLockKey {
            deck_position: self._fields.0.unwrap(),
            scalar: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod shuffle_deck_state {

    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Deck;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Deck = Unset;
    }
    ///State transition - sets the `deck` field to Set
    pub struct SetDeck<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDeck<S> {}
    impl<S: State> State for SetDeck<S> {
        type Deck = Set<members::deck>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `deck` field
        pub struct deck(());
    }
}

/// Builder for constructing an instance of this type
pub struct ShuffleDeckBuilder<'a, S: shuffle_deck_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Vec<Bytes>>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> ShuffleDeck<'a> {
    /// Create a new builder for this type
    pub fn new() -> ShuffleDeckBuilder<'a, shuffle_deck_state::Empty> {
        ShuffleDeckBuilder::new()
    }
}

impl<'a> ShuffleDeckBuilder<'a, shuffle_deck_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ShuffleDeckBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ShuffleDeckBuilder<'a, S>
where
    S: shuffle_deck_state::State,
    S::Deck: shuffle_deck_state::IsUnset,
{
    /// Set the `deck` field (required)
    pub fn deck(
        mut self,
        value: impl Into<Vec<Bytes>>,
    ) -> ShuffleDeckBuilder<'a, shuffle_deck_state::SetDeck<S>> {
        self._fields.0 = Option::Some(value.into());
        ShuffleDeckBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ShuffleDeckBuilder<'a, S>
where
    S: shuffle_deck_state::State,
    S::Deck: shuffle_deck_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> ShuffleDeck<'a> {
        ShuffleDeck {
            deck: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> ShuffleDeck<'a> {
        ShuffleDeck {
            deck: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod verify_seed_state {

    pub use crate::lexicon::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Seed;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Seed = Unset;
    }
    ///State transition - sets the `seed` field to Set
    pub struct SetSeed<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSeed<S> {}
    impl<S: State> State for SetSeed<S> {
        type Seed = Set<members::seed>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `seed` field
        pub struct seed(());
    }
}

/// Builder for constructing an instance of this type
pub struct VerifySeedBuilder<'a, S: verify_seed_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Bytes>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> VerifySeed<'a> {
    /// Create a new builder for this type
    pub fn new() -> VerifySeedBuilder<'a, verify_seed_state::Empty> {
        VerifySeedBuilder::new()
    }
}

impl<'a> VerifySeedBuilder<'a, verify_seed_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        VerifySeedBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> VerifySeedBuilder<'a, S>
where
    S: verify_seed_state::State,
    S::Seed: verify_seed_state::IsUnset,
{
    /// Set the `seed` field (required)
    pub fn seed(
        mut self,
        value: impl Into<Bytes>,
    ) -> VerifySeedBuilder<'a, verify_seed_state::SetSeed<S>> {
        self._fields.0 = Option::Some(value.into());
        VerifySeedBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> VerifySeedBuilder<'a, S>
where
    S: verify_seed_state::State,
    S::Seed: verify_seed_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> VerifySeed<'a> {
        VerifySeed {
            seed: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> VerifySeed<'a> {
        VerifySeed {
            seed: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}
